fps: 240
fullscreen: false
name: OctoPy RythmGame v
os_type: Windows
show_fps: true
version: 0.1
volume: 100

controls:
  base0: j
  base1: k
  base2: l
  base3: m
  base4: q
  base5: s
  base6: d
  base7: f
